# foundry.toml

[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.20'
# Añade estas dos líneas para que Foundry cargue el .env automáticamente
auto_detect_solc = false
force_revert = false
ffi = false
build_info = true

# Añade esta sección completa para definir nuestras redes
[rpc_endpoints]
worldchain_testnet = "${WORLD_CHAIN_TESTNET_RPC_URL}"